### ISSUE TITLE
Stops working when latest versions of json8-patch and json8-pointer are both installed

### ISSUE THREAD

**Issue by chorpler** [JSON8/patch#26]
I don't know if this has happened to anybody else, but on my Angular 5 project, I ran `npm install` in a new clone of my project, and it installed `json8-patch@0.4.0` and `json8-pointer@0.7.0`, json8-patch stopped working, at least for `.add()` and `.apply()` operations.

At first it gave `walk is not a function` errors in `add.js`, because `walk()`, which is imported from `json8-pointer`, was not exported in the `json8-pointer@0.7.0` index.js file. After I fixed that, however, it still didn't work, because apparently the walk function has been changed to use the import `@fuba/walk` in `json8-pointer@0.7.0`, and that walk function works differently than the built-in walk function that existed in `json8-pointer@0.5.0`.  And apparently if you have both `json8-patch` and `json8-pointer` installed in your project, `json8-patch` will use the already-installed `json8-pointer` instead of its own `"json8-pointer": "^0.5.0"` dependency.

**Comment by sonnyp** [comment]
sorry about that, looking into it now

**Comment by sonnyp** [comment]
thanks for the issue report, fixed in version 0.4.1
