### ISSUE TITLE
Slow performance and large size

### ISSUE THREAD

**Issue by Akkuma** [JSON8/patch#4]
Compared to alternative implementations it comes out to be roughly 2-3x slower and is also larger in size 
http://jsperf.com/json-patch-benchmark/2

**Comment by sonnyp** [comment]
> is also larger in size

What do you refer to?

I never took the time to optimize JSON8/patch but it should be easy to reach bruth implementation performances. https://github.com/Starcounter-Jack/JSON-Patch is faster but is not standard compliant

**Comment by Akkuma** [comment]
Larger in size refers to file size. Only Jiff appears to be larger, but its performance is comparable to the others.

**Comment by sonnyp** [comment]
About large file; JSON8/patch offers more functionally. But you might not need them them all. You can browserify/webpack/require only the one you need.

`require('json8-patch/lib/apply')`

**Comment by sonnyp** [comment]
About performance, thanks, I'll have a look into it.
https://github.com/JSON8/patch/issues/4
